### ISSUE TITLE
responsiveness 

### ISSUE THREAD

**Issue by PankajSingh2003** [PankajSingh2003/NASA_startingpage#17]
If anyone has any idea how can i make it mroe responsive can just comment here. Or can guide me how can i do it. Or they can do it themselves.

**Comment by Burekslayer** [comment]
Hello, I'm kinda new to github and contribution to open source (jobs in general). I could try to help out with these issues.

**Comment by PankajSingh2003** [comment]
Go ahead mate!!!
Your help is more than appreciated.

**Comment by Burekslayer** [comment]
The paragraph and Carl Sagans' sentence are supposed to be a bit to the right of the center? Or should I change that as well?

**Comment by PankajSingh2003** [comment]
Go ahead.
Try it. let's see
