### ISSUE TITLE
Fix the postioning of the images in the webpage

### ISSUE THREAD

**Issue by PankajSingh2003** [PankajSingh2003/NASA_startingpage#18]
If anyone can fix the postioning of images in the webpage. for all the devices it will be more than helpful

**Comment by anubhav2102** [comment]
Can i work on this issue?

**Comment by PankajSingh2003** [comment]
Sure go ahead. (well you can try making it for all the devices if you can )

**Comment by Kritika30032002** [comment]
is this still available?

**Comment by anubhav2102** [comment]
I am working on it

> is this still available?

**Comment by Kritika30032002** [comment]
> 

It has been 3 days now. Is it taking this much long time?
I can do this If you are not able to do it.
