### ISSUE TITLE
If anyone has any more idea can leave it here 

### ISSUE THREAD

**Issue by PankajSingh2003** [PankajSingh2003/NASA_startingpage#19]
Your idea what to do.

**Comment by vatsalsinghkv** [comment]
It'd be better if you structure your code. It's really messy

**Comment by PankajSingh2003** [comment]
Thanks for the feedback!!!!
Yes i know the code is messy now. But onece all the conctributions are done. And the website starts to look clean .
I will make this repo simple and easy to understand.

**Comment by PankajSingh2003** [comment]
Well i have structed it now.
Thanks everyone for the waiting i was just waiting so that everyone is able to see the files in one file only as it is easier to work that way.

**Comment by vatsalsinghkv** [comment]
@PankajSingh2003  It's good that you structured the code, but you completely missed the point here. We structure code so it's easy for everyone to contribute, it was so hard to understand the app where all the files are put together in one folder.

**Comment by PankajSingh2003** [comment]
Thanks man for the feedback. Will  structure it the next time i open any webpge  for contribution.
