### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by PankajSingh2003** [PankajSingh2003/NASA_startingpage#23]
Can someone add a nice social media footer and the end.

**Comment by Burekslayer** [comment]
I can work on this.

**Comment by PankajSingh2003** [comment]
Go ahead mate !!!!.

**Comment by Ayush-Kori** [comment]
Hey can I work on this issue

**Comment by Kritika30032002** [comment]
May I contribute to this?

**Comment by PankajSingh2003** [comment]
Sure go ahead. (please if you can try to making it for mobile devices as well.

**Comment by Kritika30032002** [comment]
> Sure go ahead. (please if you can try to making it for mobile devices as well.

@PankajSingh2003  you can assign me this!
