### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by PankajSingh2003** [PankajSingh2003/NASA_startingpage#28]
If anyone know how to make a alluring and amazing navbar.
You are more than welcome here.

**Comment by Davethadev** [comment]
I've been able to come up with a navbar. It's neither amazing nor alluring tho😅
It's just really basic but I made it responsive (: 
You can check it out here
https://davethadev.github.io/NASA_startingpage/#
If you have a specific design you'd like for the website navbar you could show me and I'll try to implement it

**Comment by PankajSingh2003** [comment]
Make a pull request lets see if can fix or not.

**Comment by PankajSingh2003** [comment]
By the way thanks for the effor that you have made 
seriously man Thank you !!!!!
more than appreciated.

**Comment by Davethadev** [comment]
I've just made a pull request
You're very welcome 
Glad I could contribute!!!

**Comment by PankajSingh2003** [comment]
Thanks again for your contribution.
