### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by PankajSingh2003** [PankajSingh2003/NASA_startingpage#29]
If anyone has any knowledge about how we can add a dark mode  switch on the website.
Then try putting it to the website and make a pull request.

Thanks in advance for the efforts you are about to made.

**Comment by subinoybiswas** [comment]
where is the website code?

**Comment by PankajSingh2003** [comment]
index.html file the main code and css file is style.css if you want to add javascript then script.js

**Comment by Ved142** [comment]
Hey @PankajSingh2003 I would like to work on it. Please assign it to me.

**Comment by vatsalsinghkv** [comment]
I can make it. Please assign this issue to me

**Comment by Iamslok** [comment]
@PankajSingh2003
A few days back I did a Light/Dark mode contribution to a project
Can you assign me, I would like to contribute.

**Comment by anmolranjan1** [comment]
Please assign me this issue @PankajSingh2003

**Comment by Kritika30032002** [comment]
@PankajSingh2003 Is this still available?
I would like to contribute !
You can assign me this

**Comment by Raissa-Cardoso** [comment]
@PankajSingh2003 I solved this in #51. Can you check this?
