### ISSUE TITLE
images are not visible

### ISSUE THREAD

**Issue by TenzinNsut** [PankajSingh2003/NASA_startingpage#37]
images are not visbile
![image](https://user-images.githubusercontent.com/105097758/196679238-eb0bf686-bc4e-4028-9893-b9a6d6e918ac.png)

**Comment by Kritika30032002** [comment]
assign this to me !!

**Comment by manojku1803** [comment]
![Uploading image.png…]()

Pictures are visible

**Comment by PankajSingh2003** [comment]
Sure go ahead. Your help is more than appreciated.
