### ISSUE TITLE
Suggestion to contribute: responsiveness for extra-large screens and minor fixes

### ISSUE THREAD

**Issue by mhenrique94** [PankajSingh2003/NASA_startingpage#39]
Hello! Congrats for the project, I just tested and it's really fun to go around! I have some suggestions, please let me know if I can PR (after the other 2 PR's already open).

They are: 

- Fix the responsiveness of main text on home, on extra-wide screen the text comes to the center and overlap the planet, making all difficult to read;
- Button hover on navbar instead of underlying each link;
- make each section (with planet and text) to occupy the whole height, to a more immersive experience.

Please let me know I fan can PR any or all of the above.

See you!

**Comment by PankajSingh2003** [comment]
Sure man . Think you have ellaborated more than enough.
Any help from you is appreciated.
if you gave it a thought only still thanks man for your effort.

**Comment by PankajSingh2003** [comment]
I am Assigning you this just in case you decide to do that.

**Comment by mhenrique94** [comment]
Done! Can you labe it to hacktoberfest? Thanks!
