### ISSUE TITLE
Text and Profile Cards overlapping

### ISSUE THREAD

**Issue by Tatwansh** [PankajSingh2003/NASA_startingpage#46]
![image](https://user-images.githubusercontent.com/86573957/197122828-160a9f82-5c27-47eb-8096-c60ff4af8e01.png)

**Comment by Tatwansh** [comment]
hey @PankajSingh2003 I would like to work on this issue. Also please label it for Hacktober.

**Comment by PankajSingh2003** [comment]
Sure go ahead try to fix it.
Thanks for the feedback by the way : )
Good luck in case you are trying .

**Comment by Tatwansh** [comment]
Hey, I have made a pull request with the required changes in index.html as well as style.css . Please review and merge them.

**Comment by Tatwansh** [comment]
@PankajSingh2003
