### ISSUE TITLE
Footer issue

### ISSUE THREAD

**Issue by PankajSingh2003** [PankajSingh2003/NASA_startingpage#53]
The recent footer is to much at the bottom . If anyone cant fix it go ahead.

**Comment by super-duper-sp** [comment]
Please assign it to me

**Comment by PankajSingh2003** [comment]
Sure go ahead amigo :)

**Comment by super-duper-sp** [comment]
hey @PankajSingh2003 , I have solved the footer issue. please check PR #60  and add hacktoberfest label to it.

Note: a screenshot of footer

<img width="1431" alt="footerfixed" src="https://user-images.githubusercontent.com/68178609/197700790-20f0ca07-30a6-4aa4-9092-f3fa481ec799.png">

**Comment by PankajSingh2003** [comment]
Already accepted your pr mate
