### ISSUE TITLE
Parker Solar probe

### ISSUE THREAD

**Issue by PankajSingh2003** [PankajSingh2003/NASA_startingpage#54]
Parker solar probe at the beginning of the webpage isn't showing on mobile devices. 
as it is the front page . Any one who can solve it is more than appreciate it.

**Comment by alabador** [comment]
Hello, can I work on this issue?

**Comment by PankajSingh2003** [comment]
Sure go ahead.

**Comment by alabador** [comment]
Issue is solved in #62. Feel free to check when you're available, thanks!
