### ISSUE TITLE
Footer isn't properly showing for mobile devices

### ISSUE THREAD

**Issue by PankajSingh2003** [PankajSingh2003/NASA_startingpage#56]
if anyone can make it responsive for mobile devices.
It would really help.

**Comment by Summiedev** [comment]
Assign me this please

**Comment by PankajSingh2003** [comment]
Sure. :)

**Comment by Arcturus22** [comment]
@PankajSingh2003 
I want to resolve this issue. Please assign me this issue.

**Comment by PankajSingh2003** [comment]
Well i think someone is already working on it. 
still if you want you can try i will accept the :)
Thanks in advance .
