### ISSUE TITLE
Hover the underline color left to right

### ISSUE THREAD

**Issue by Yasshu55** [PankajSingh2003/NASA_startingpage#68]
For the _Parker Solar Probe_ text shown on the homepage, i would Iike to add a left to right hovering effect when hovering over the text.

Please assign me this issue under hactoberfest

![Screenshot 2022-10-25 160141](https://user-images.githubusercontent.com/95294297/197751371-e88df3ec-8464-428c-a099-bf635d0eafe2.png)

**Comment by PankajSingh2003** [comment]
Sure go ahead love your issue.
by the way :)

**Comment by PankajSingh2003** [comment]
There you go added the labeles as well.
Hope you have a wonderfull day ahead : )

**Comment by Yasshu55** [comment]
@PankajSingh2003 Is there any color preference for the text during the transition? or should i go ahead with any color that might look good

**Comment by PankajSingh2003** [comment]
You can choose whatever the color you like the most :)
